### PR TITLE
First hello

### PR DESCRIPTION
**Pull request by Cabraham1**
created HTML file add h1 header tag
created CSS file added some background styles

### CODE REVIEW

**Comment by Cabraham1** [comment]
you just so fuuny i tell you ...

**Comment by Cabraham1** [comment]
@nedjwab where exactly should i make this changes?
is it on my read me file or on github pr section?

**Comment by nedjwab** [comment]
> @nedjwab where exactly should i make this changes? is it on my read me file or on github pr section?

On your pull request summary, instead of creating my .... , Add more details about what you did on this project example : create html file , add css....

**Comment by Cabraham1** [comment]
> > @nedjwab where exactly should i make this changes? is it on my read me file or on github pr section?
> 
> On your pull request summary, instead of creating my .... , Add more details about what you did on this project example : create html file , add css....

I can not find the PR summary section except I close this PR and start over again.
what should I do now

**Review by Santiago220991 — APPROVED** [review]
Hi @Cabraham1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: Followed GitHub flow.

## Optional suggestions
[OPTIONAL] Kindly remember that the PR summary should include a descriptive title. Please remember this in future projects.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
